name: New Platform Request
description: Request a new MCP server for a platform not yet supported
title: "[NEW PLATFORM] "
labels: ["new-platform", "enhancement"]
body:
  - type: input
    id: platform
    attributes:
      label: Platform Name
      description: What platform would you like to see supported?
      placeholder: e.g., Slack, Microsoft Teams, Jira, etc.
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Platform Website
      description: Official website or documentation URL
      placeholder: https://...
    validations:
      required: true
  - type: textarea
    id: api-info
    attributes:
      label: API Information
      description: What do you know about their API?
      placeholder: |
        - API Documentation URL:
        - Authentication method:
        - Rate limits:
        - Key features to integrate:
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Business Use Case
      description: How would this integration be used?
      placeholder: Describe the business value and use cases
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this integration?
      options:
        - High - Critical for business operations
        - Medium - Would significantly improve workflows
        - Low - Nice to have
    validations:
      required: true
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I have API access to test this platform
        - label: I can provide API documentation
        - label: I'm willing to help with development
        - label: I can help with testing